const inquirer = require("inquirer").default
const styles = require("./index.js")

async function runFullSuites() {
  console.log("🚀 Starting Comprehensive AnsiStyles Test Suite\n")

  const suites = [
    {
      name: "MODIFIERS",
      items: [
        { label: "reset", style: styles.modifier.reset },
        { label: "bold", style: styles.modifier.bold },
        { label: "dim", style: styles.modifier.dim },
        { label: "italic", style: styles.modifier.italic },
        { label: "underline", style: styles.modifier.underline },
        { label: "overline", style: styles.modifier.overline },
        { label: "inverse", style: styles.modifier.inverse },
        { label: "hidden", style: styles.modifier.hidden },
        { label: "strikethrough", style: styles.modifier.strikethrough }
      ]
    },
    {
      name: "FOREGROUND COLORS",
      items: [
        { label: "black", style: styles.color.black },
        { label: "red", style: styles.color.red },
        { label: "green", style: styles.color.green },
        { label: "yellow", style: styles.color.yellow },
        { label: "blue", style: styles.color.blue },
        { label: "magenta", style: styles.color.magenta },
        { label: "cyan", style: styles.color.cyan },
        { label: "white", style: styles.color.white },
        { label: "blackBright (gray)", style: styles.color.blackBright },
        { label: "redBright", style: styles.color.redBright },
        { label: "greenBright", style: styles.color.greenBright },
        { label: "yellowBright", style: styles.color.yellowBright },
        { label: "blueBright", style: styles.color.blueBright },
        { label: "magentaBright", style: styles.color.magentaBright },
        { label: "cyanBright", style: styles.color.cyanBright },
        { label: "whiteBright", style: styles.color.whiteBright }
      ]
    },
    {
      name: "BACKGROUND COLORS",
      items: [
        { label: "bgBlack", style: styles.bgColor.bgBlack },
        { label: "bgRed", style: styles.bgColor.bgRed },
        { label: "bgGreen", style: styles.bgColor.bgGreen },
        { label: "bgYellow", style: styles.bgColor.bgYellow },
        { label: "bgBlue", style: styles.bgColor.bgBlue },
        { label: "bgMagenta", style: styles.bgColor.bgMagenta },
        { label: "bgCyan", style: styles.bgColor.bgCyan },
        { label: "bgWhite", style: styles.bgColor.bgWhite },
        { label: "bgBlackBright", style: styles.bgColor.bgBlackBright },
        { label: "bgRedBright", style: styles.bgColor.bgRedBright },
        { label: "bgGreenBright", style: styles.bgColor.bgGreenBright },
        { label: "bgYellowBright", style: styles.bgColor.bgYellowBright },
        { label: "bgBlueBright", style: styles.bgColor.bgBlueBright },
        { label: "bgMagentaBright", style: styles.bgColor.bgMagentaBright },
        { label: "bgCyanBright", style: styles.bgColor.bgCyanBright },
        { label: "bgWhiteBright", style: styles.bgColor.bgWhiteBright }
      ]
    }
  ]

  for (const suite of suites) {
    console.log(`\n=== ${suite.name} ===`)
    for (const item of suite.items) {
      // Testing the .open and .close properties generated by your package logic
      const sample = `${item.style.open}  TESTING: ${item.label}  ${item.style.close}`
      console.log(sample)

      const res = await inquirer.prompt([{
        type: "confirm",
        name: "ok",
        message: `Confirm ${item.label}:`,
        default: true
      }])

      if (!res.ok) {
        console.log(`❌ Failed visual match for: ${item.label}`)
        process.exit(1)
      }
    }
  }

  console.log("\n--- Testing RGB to Ansi256 (Grayscale Gradient) ---")
  let grayscale = ""
  for (let i = 0; i < 24; i++) {
    const code = 232 + i
    grayscale += `\u001B[48;5;${code}m  `
  }
  console.log(grayscale + "\u001B[0m\n")

  const mathRes = await inquirer.prompt([{
    type: "confirm",
    name: "ok",
    message: "Is the grayscale gradient displayed correctly?",
    default: true
  }])

  if (mathRes.ok) {
    console.log("\n✨ ALL TESTS PASSED: Every style sequence verified.")
  } else {
    console.log("\n❌ Math conversion logic failed.")
    process.exit(1)
  }
}

runFullSuites()